#!/usr/bin/env python26
'''
Mark STacy - markstacy@ou.edu
01/19/2011
Command line tool for retrieving Ameriflux Data:
SYNOPSIS:
    AMFdata SiteID Years Type [Variables]
    
    SiteID <string>, Years <Comma delimited string>,Type <string {TDF_M,TDF_W,TDF_D,TDF_H}
    Variables <Comma delimited string>
EXAMPLE:
    AMFdata uS-ha1 1999,2005,2006 TDF_M PRECIP,GPP_OR_ANN
'''
import syncWS as sync
import sys

def getRows4(site,year,type,col):
    sync.getAMF_SiteID(site,year,type,col)
def getRows3(site,year,type):
    sync.getAMF_SiteID(site,year,type)
def main(argv = None):
    if argv is None:
        argv = sys.argv
    options = {}
    if len(argv)==5:
        options.update(siteID=argv[1],mYear=argv[2],Type=argv[3],Columns=argv[4])
        return getRows4(options['siteID'], options['mYear'], options['Type'],options['Columns'])
    else:
        options.update(siteID=argv[1],mYear=argv[2],Type=argv[3])
        return getRows3(options['siteID'], options['mYear'], options['Type'])

if __name__ == "__main__":
    sys.exit(main())
