#!/usr/bin/env python26
"""
Mark STacy - markstacy@ou.edu
01/19/2011
Command line tool for retrieving EOMF Data:
SYNOPSIS:
    EOMFdata LAT LON Years Type [Variables]
    
    LAT, LON, product ,year(s) <Comma delimited>
    Variables <Comma delimited string>
EXAMPLE:
    EOMFdata 35.034 -99.8437 mod09a1 2009,2001 REAL_DATE
"""
import syncWS as sync
import sys

def getRows5(LAT,LON,year,type,col):
    sync.getEOMFdata(LAT,LON,year,type,col)
def getRows4(LAT,LON,year,type):
    sync.getEOMFdata(LAT,LON,year,type)
def main(argv = None):
    if argv is None:
        argv = sys.argv
    options = {}
    if len(argv)==6:
        options.update(LAT=argv[1],LON=argv[2],product=argv[3],myear=argv[4],Columns=argv[5])
        return getRows5(options['LAT'],options['LON'], options['product'], options['myear'],options['Columns'])
    else:
        options.update(LAT=argv[1],LON=argv[2],product=argv[3],myear=argv[4])
        return getRows4(options['LAT'], options['LON'], options['product'], options['myear'])

if __name__ == "__main__":
    sys.exit(main())
