r.neighbors input=bio1@WORLDCLIM output=bio1_avg_3_km size=3 method=average
r.neighbors input=bio1@WORLDCLIM output=bio1_range_3_km size=3 method=range
r.neighbors input=bio3@WORLDCLIM output=bio3_avg_3_km size=3 method=average
r.neighbors input=bio3@WORLDCLIM output=bio3_range_3_km size=3 method=range
r.neighbors input=bio7@WORLDCLIM output=bio7_avg_3_km size=3 method=average
r.neighbors input=bio7@WORLDCLIM output=bio7_range_3_km size=3 method=range
r.neighbors input=bio9@WORLDCLIM output=bio9_avg_3_km size=3 method=average
r.neighbors input=bio9@WORLDCLIM output=bio9_range_3_km size=3 method=range
r.neighbors input=bio12@WORLDCLIM output=bio12_avg_3_km size=3 method=average
r.neighbors input=bio12@WORLDCLIM output=bio12_range_3_km size=3 method=range
r.neighbors input=bio19@WORLDCLIM output=bio19_avg_3_km size=3 method=average
r.neighbors input=bio19@WORLDCLIM output=bio19_range_3_km size=3 method=range
r.neighbors input=bio1@WORLDCLIM output=bio1_avg_5_km size=5 method=average
r.neighbors input=bio1@WORLDCLIM output=bio1_range_5_km size=5 method=range
r.neighbors input=bio3@WORLDCLIM output=bio3_avg_5_km size=5 method=average
r.neighbors input=bio3@WORLDCLIM output=bio3_range_5_km size=5 method=range
r.neighbors input=bio7@WORLDCLIM output=bio7_avg_5_km size=5 method=average
r.neighbors input=bio7@WORLDCLIM output=bio7_range_5_km size=5 method=range
r.neighbors input=bio9@WORLDCLIM output=bio9_avg_5_km size=5 method=average
r.neighbors input=bio9@WORLDCLIM output=bio9_range_5_km size=5 method=range
r.neighbors input=bio12@WORLDCLIM output=bio12_avg_5_km size=5 method=average
r.neighbors input=bio12@WORLDCLIM output=bio12_range_5_km size=5 method=range
r.neighbors input=bio19@WORLDCLIM output=bio19_avg_5_km size=5 method=average
r.neighbors input=bio19@WORLDCLIM output=bio19_range_5_km size=5 method=range
r.neighbors input=bio1@WORLDCLIM output=bio1_avg_15_km size=15 method=average
r.neighbors input=bio1@WORLDCLIM output=bio1_range_15_km size=15 method=range
r.neighbors input=bio3@WORLDCLIM output=bio3_avg_15_km size=15 method=average
r.neighbors input=bio3@WORLDCLIM output=bio3_range_15_km size=15 method=range
r.neighbors input=bio7@WORLDCLIM output=bio7_avg_15_km size=15 method=average
r.neighbors input=bio7@WORLDCLIM output=bio7_range_15_km size=15 method=range
r.neighbors input=bio9@WORLDCLIM output=bio9_avg_15_km size=15 method=average
r.neighbors input=bio9@WORLDCLIM output=bio9_range_15_km size=15 method=range
r.neighbors input=bio12@WORLDCLIM output=bio12_avg_15_km size=15 method=average
r.neighbors input=bio12@WORLDCLIM output=bio12_range_15_km size=15 method=range
r.neighbors input=bio19@WORLDCLIM output=bio19_avg_15_km size=15 method=average
r.neighbors input=bio19@WORLDCLIM output=bio19_range_15_km size=15 method=range
r.neighbors input=bio1@WORLDCLIM output=bio1_avg_47_km size=47 method=average
r.neighbors input=bio1@WORLDCLIM output=bio1_range_47_km size=47 method=range
r.neighbors input=bio3@WORLDCLIM output=bio3_avg_47_km size=47 method=average
r.neighbors input=bio3@WORLDCLIM output=bio3_range_47_km size=47 method=range
r.neighbors input=bio7@WORLDCLIM output=bio7_avg_47_km size=47 method=average
r.neighbors input=bio7@WORLDCLIM output=bio7_range_47_km size=47 method=range
r.neighbors input=bio9@WORLDCLIM output=bio9_avg_47_km size=47 method=average
r.neighbors input=bio9@WORLDCLIM output=bio9_range_47_km size=47 method=range
r.neighbors input=bio12@WORLDCLIM output=bio12_avg_47_km size=47 method=average
r.neighbors input=bio12@WORLDCLIM output=bio12_range_47_km size=47 method=range
r.neighbors input=bio19@WORLDCLIM output=bio19_avg_47_km size=47 method=average
r.neighbors input=bio19@WORLDCLIM output=bio19_range_47_km size=47 method=range
r.neighbors input=bio1@WORLDCLIM output=bio1_avg_141_km size=141 method=average
r.neighbors input=bio1@WORLDCLIM output=bio1_range_141_km size=141 method=range
r.neighbors input=bio3@WORLDCLIM output=bio3_avg_141_km size=141 method=average
r.neighbors input=bio3@WORLDCLIM output=bio3_range_141_km size=141 method=range
r.neighbors input=bio7@WORLDCLIM output=bio7_avg_141_km size=141 method=average
r.neighbors input=bio7@WORLDCLIM output=bio7_range_141_km size=141 method=range
r.neighbors input=bio9@WORLDCLIM output=bio9_avg_141_km size=141 method=average
r.neighbors input=bio9@WORLDCLIM output=bio9_range_141_km size=141 method=range
r.neighbors input=bio12@WORLDCLIM output=bio12_avg_141_km size=141 method=average
r.neighbors input=bio12@WORLDCLIM output=bio12_range_141_km size=141 method=range
r.neighbors input=bio19@WORLDCLIM output=bio19_avg_141_km size=141 method=average
r.neighbors input=bio19@WORLDCLIM output=bio19_range_141_km size=141 method=range
