CREATE SCHEMA "ECO";

CREATE TABLE "ECO"."DT_CATALOG" ( 
	"CAT_ID" numeric  NOT NULL,
	"CAT_NAME" varchar( 150 )  NULL,
	"DESCRIPTION" varchar( 1000 )  NULL,
	"TYPE_ID" varchar( 255 )  NULL,
	"TIME_ID" numeric  NULL,
	"LOC_ID" numeric  NULL,
CONSTRAINT PK_DT_CATALOG PRIMARY KEY ( "CAT_ID" )
 ) ;

CREATE INDEX idx_DT_CATALOG_1 ON "ECO"."DT_CATALOG" ( "TYPE_ID" );

CREATE INDEX IDX_DT_CATALOG ON "ECO"."DT_CATALOG" ( "LOC_ID" );

CREATE INDEX IDX_DT_CATALOG_0 ON "ECO"."DT_CATALOG" ( "TIME_ID" );

COMMENT ON TABLE "ECO"."DT_CATALOG" IS 'Catalog and Inventory of available data for Cybercommons.';

COMMENT ON COLUMN "ECO"."DT_CATALOG"."CAT_NAME" IS 'Descriptive name that logically describes data.';

COMMENT ON COLUMN "ECO"."DT_CATALOG"."DESCRIPTION" IS 'Detail Description of Data.';

COMMENT ON COLUMN "ECO"."DT_CATALOG"."TYPE_ID" IS 'Index to TYPE TABLE.';

CREATE TABLE "ECO"."DT_LOCATION" ( 
	"LOC_ID" numeric  NOT NULL,
	"DT_TYPE" varchar( 150 )  NULL,
	"LOC_X" float4  NULL,
	"LOC_Y" float4  NULL,
	"NORTHBOUNDING" float4  NULL,
	"SOUTHBOUNDING" float4  NULL,
	"EASTBOUNDING" float4  NULL,
	"WESTBOUNDING" float4  NULL,
	"COORD_SYSTEM" varchar( 255 )  NULL,
CONSTRAINT PK_DT_LOCATION PRIMARY KEY ( "LOC_ID" )
 ) ;

CREATE TABLE "ECO"."DT_PARAMETER" ( 
	"CAT_ID" numeric  NOT NULL,
	"PARAM_ID" numeric  NOT NULL,
	"DESCRIPTION" varchar( 255 )  NULL,
	"VALUE" varchar( 255 )  NULL,
	"VALUE_DTYPE" varchar( 255 )  NULL,
	"PARAM_ORDER" numeric  NULL,
CONSTRAINT Idx_DT_PARAMETER PRIMARY KEY ( "PARAM_ID", "CAT_ID" )
 ) ;

COMMENT ON TABLE "ECO"."DT_PARAMETER" IS 'Holds Parameter of data calls in which the data is stored in cache.';

COMMENT ON COLUMN "ECO"."DT_PARAMETER"."VALUE_DTYPE" IS 'INT, Double,String,...ect. 
Need to set Data Type Standard. For reading Parameter list.';

COMMENT ON COLUMN "ECO"."DT_PARAMETER"."PARAM_ORDER" IS 'ORDER TO RECIEVE IN DATA CALL';

CREATE TABLE "ECO"."DT_SOURCE" ( 
	"CAT_ID" numeric  NOT NULL,
	"SOURCE_ID" numeric  NOT NULL,
	"LOC_STATUS" varchar( 15 )  NULL,
	"SOURCE_NAME" varchar( 255 )  NULL,
	"PATH" varchar( 255 )  NULL,
	"PATH_DESC" varchar( 500 )  NULL,
CONSTRAINT IDX_DT_SOURCE PRIMARY KEY ( "CAT_ID", "SOURCE_ID" )
 ) ;

COMMENT ON TABLE "ECO"."DT_SOURCE" IS 'Metadata describing the origin of the Data.			';

COMMENT ON COLUMN "ECO"."DT_SOURCE"."CAT_ID" IS 'Primary Key';

COMMENT ON COLUMN "ECO"."DT_SOURCE"."LOC_STATUS" IS 'Local or Virtual';

COMMENT ON COLUMN "ECO"."DT_SOURCE"."SOURCE_NAME" IS 'Source Name';

COMMENT ON COLUMN "ECO"."DT_SOURCE"."PATH" IS 'URL or the file path and filename where data is located.';

COMMENT ON COLUMN "ECO"."DT_SOURCE"."PATH_DESC" IS 'Description of Path and need parameters. (x,y, bounding box....ect)';

CREATE TABLE "ECO"."DT_TEMPORAL" ( 
	"TIME_ID" numeric  NOT NULL,
	"DESCRIPTION" varchar( 255 )  NULL,
	"TEMPORAL_GRANULARITY" varchar( 255 )  NULL,
	"ITEM_DATE" varchar( 255 )  NULL,
	"START_DATE" date  NULL,
	"END_DATE" date  NULL,
	"YEAR" varchar( 25 )  NULL,
	"DAY_OF_YEAR" numeric  NULL,
CONSTRAINT PK_DT_TEMPORAL PRIMARY KEY ( "TIME_ID" )
 ) ;

COMMENT ON TABLE "ECO"."DT_TEMPORAL" IS 'Description of time that data covers';

COMMENT ON COLUMN "ECO"."DT_TEMPORAL"."ITEM_DATE" IS 'Date used in data item ';

CREATE TABLE "ECO"."DT_TYPE" ( 
	"TYPE_ID" varchar( 255 )  NOT NULL,
	"TYPE_NAME" varchar( 255 )  NULL,
	"PRODUCT" varchar( 255 )  NULL,
	"DESCRIPTION" varchar( 255 )  NULL,
	"RESOLUTION" varchar( 255 )  NULL,
	"RES_UNIT" varchar( 50 )  NULL,
	"OBJECT_TYPE" varchar( 100 )  NULL,
	"OBJECT_DATA_OPT1" varchar( 255 )  NULL,
	"OBJECT_DATA_OPT1_UNIT" varchar( 100 )  NULL,
CONSTRAINT PK_Table PRIMARY KEY ( "TYPE_ID" )
 ) ;

COMMENT ON TABLE "ECO"."DT_TYPE" IS 'Describes the type of data that it catalogs.';

COMMENT ON COLUMN "ECO"."DT_TYPE"."TYPE_ID" IS 'PK For Types';

ALTER TABLE "ECO"."DT_CATALOG" ADD CONSTRAINT FK_DT_CATALOG_0 FOREIGN KEY ( "TYPE_ID" ) REFERENCES "ECO"."DT_TYPE"( "TYPE_ID" ) ON DELETE CASCADE ;

ALTER TABLE "ECO"."DT_CATALOG" ADD CONSTRAINT FK_DT_CATALOG FOREIGN KEY ( "LOC_ID" ) REFERENCES "ECO"."DT_LOCATION"( "LOC_ID" ) ON DELETE CASCADE ;

ALTER TABLE "ECO"."DT_CATALOG" ADD CONSTRAINT FK_DT_CATALOG_1 FOREIGN KEY ( "TIME_ID" ) REFERENCES "ECO"."DT_TEMPORAL"( "TIME_ID" ) ON DELETE CASCADE ;

ALTER TABLE "ECO"."DT_PARAMETER" ADD CONSTRAINT FK_DT_PARAMETER FOREIGN KEY ( "CAT_ID" ) REFERENCES "ECO"."DT_CATALOG"( "CAT_ID" ) ON DELETE CASCADE ;

ALTER TABLE "ECO"."DT_SOURCE" ADD CONSTRAINT FK_DT_SOURCE FOREIGN KEY ( "CAT_ID" ) REFERENCES "ECO"."DT_CATALOG"( "CAT_ID" ) ON DELETE CASCADE ;

