function y=Generate(c_op,transT,eigV,cmin,cmax)
while(true)
    cT=randn(7,1).*[sqrt(eigV(1,1));sqrt(eigV(2,2));sqrt(eigV(3,3));sqrt(eigV(4,4));sqrt(eigV(5,5));sqrt(eigV(6,6));sqrt(eigV(7,7))];
    c_new =transT*(transT'*c_op+cT);%generate a new configuration based on the estimated covariance matrix
    if  (c_new(1)>cmin(1)&c_new(1)<cmax(1)...
        &c_new(2)>cmin(2)&c_new(2)<cmax(2)...
        &c_new(3)>cmin(3)&c_new(3)<cmax(3)...
        &c_new(4)>cmin(4)&c_new(4)<cmax(4)...
        &c_new(5)>cmin(5)&c_new(5)<cmax(5)...
        &c_new(6)>cmin(6)&c_new(6)<cmax(6)...
        &c_new(7)>cmin(7)&c_new(7)<cmax(7))
        break
    end
end
% while(true)
%     c_new=c_op+(rand(7,1)-0.5).*(cmax-cmin)'/5;
%     if  (c_new(1)>cmin(1)&c_new(1)<cmax(1)...
%         &c_new(2)>cmin(2)&c_new(2)<cmax(2)...
%         &c_new(3)>cmin(3)&c_new(3)<cmax(3)...
%         &c_new(4)>cmin(4)&c_new(4)<cmax(4)...
%         &c_new(5)>cmin(5)&c_new(5)<cmax(5)...
%         &c_new(6)>cmin(6)&c_new(6)<cmax(6)...
%         &c_new(7)>cmin(7)&c_new(7)<cmax(7))
%         disp('hi');
%     
%         break;
%     end
% end

y=c_new;
