mongo_clusters:
    - host: fire.rccc.ou.edu
      port: 27017
      replicaset: cybercom
      
catalog:
    - host: fire.rccc.ou.edu
      type: postgresql
      production: True
      database: catalog
      port: 5432
    - host: fire.rccc.ou.edu
      type: mongodb
      port: 27017
      production: False
      database: catalog

wsgi_servers:
    - name: test
      host: test.cybercommons.org
      appdir: /var/www/apps/
      type: apache
      production: False
      mod_authtkt: True
    - name: production
      host: production.cybercommons.org
      appdir: /var/www/apps/
      type: apache
      production: True
      mod_authtkt: True

static_servers:
    - name: static
      host: static.cybercommons.org
      dir: /static/
      type: nginx

queue: 
    - name: cybercom_queue
      type: rabbitmq
      host: fire.rccc.ou.edu
      broker_vhost: cybercom_test
      broker_password: cybercommons
      celerybackend:
        host: fire.rccc.ou.edu
        database: cybercom_queue
        taskmeta_collection: cybercom_queue_meta

celery_workers:
    - name: static
      host: static.cybercommons.org
      type: RHEL6
      dir: /opt/celeryq/
    - name: gis
      host: 129.15.41.74
      type: SCILIN6
      dir: /opt/celeryq/
    - name: earth
      defaultq: True
      host: earth.cybercommons.org
      type: RHEL5
      dir: /opt/celeryq
    - name: arcgis
      host: 129.15.41.83
      type: RHEL5
      dir: /opt/celeryq
