mongo:
    - host: fire.rccc.ou.edu
      port: 27017
      replicaset: cybercom
    - host: 129.15.41.76
      port: 27017
      replicaset: cybercom
 
catalog:
    - host: fire.rccc.ou.edu
      type: postgresql
      production: True
      database: catalog
      port: 5432
    - host: fire.rccc.ou.edu
      type: mongodb
      port: 27017
      production: False
      database: catalog

varnish:
    - host: cache.cybercommons.org

wsgi:
    - name: test
      host: test.cybercommons.org
      appdir: /var/www/apps/
      type: apache
      production: False
      mod_authtkt: True
      memcache: True
    - name: production
      host: production.cybercommons.org
      appdir: /var/www/apps/
      type: apache
      production: True
      mod_authtkt: True
      memcache: True

static:
    - name: static
      host: static.cybercommons.org
      dir: /static/
      type: nginx

queue: 
    - name: cybercom_queue
      type: rabbitmq
      host: fire.rccc.ou.edu
      broker_vhost: cybercom_test
      broker_password: cybercommons
      celerybackend:
        host: fire.rccc.ou.edu
        database: cybercom_queue
        taskmeta_collection: cybercom_queue_meta

workers:
    - name: static
      host: static.cybercommons.org
      type: RHEL6
      dir: /opt/celeryq/
      broker: cybercom_queue
    - name: gis
      host: 129.15.41.74
      type: SCILIN6
      dir: /opt/celeryq/
      broker: cybercom_queue
    - name: earth
      defaultq: True
      host: earth.rccc.ou.edu
      type: RHEL5
      dir: /opt/celeryq
      broker: cybercom_queue
