#!/bin/bash

upper() {
    echo $1 | tr [:lower:] [:upper:]
}
OUTDIR=/scratch/www/html/bioscatter/download

cd ${OUTDIR} 

PRODUCT=$1
PRODUCT_U=$(upper $1)
LAT=$2
LON=$3
RAD=$4
TIME=$5

DATADIR=/scratch/data/nws/ldm/tiles/mosaic/${PRODUCT}
PROJWIN=$(/home/jduckles/cybercom/bioscatter/mkwin ${LAT} ${LON} ${RAD})
if [ -f ${DATADIR}/${PRODUCT_U}.${TIME}.vrt ]; then
    gdal_translate -q -projwin ${PROJWIN} -co COMPRESS=LZW ${DATADIR}/${PRODUCT_U}.${TIME}.vrt ${PRODUCT_U}.${TIME}_${LAT}_${LON}.tif
    #echo "http://fire.rccc.ou.edu/bioscatter/download/${PRODUCT_U}.${TIME}_${LAT}_${LON}.tif"
    echo "${OUTDIR}/${PRODUCT_U}.${TIME}_${LAT}_${LON}.tif"
else
    echo "Can't find ${DATADIR}/${PRODUCT_U}.${TIME}.vrt"
fi



